name: CVE Daily Push

on:
  repository_dispatch:
    types: [Test_Dispatch]
  schedule:
    - cron: '0 0 * * *' # UTC时间比北京时间慢8小时，此处表示每天北京时间早上8点运行

jobs:
  run-python:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' # 选择您想要使用的 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Run Python script
        run: python scripts/run.py '${{ secrets.MAIL_CONFIG }}' '${{ secrets.NIST_API_KEY }}' # 替换成您的 Python 脚本文件名